name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        run: corepack enable && corepack prepare

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        run: corepack enable && corepack prepare

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        run: corepack enable && corepack prepare

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test
